version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    container_name: product-embedder
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"

